[package]
name = "mt32-volume"
description = "macOS commandline utility to set the volume of a Roland MT-32"
version = "1.0.1"
license = "GPL-3.0-only"
repository = "https://github.com/mistydemeo/mt32-volume"
binaries = ["mt32-volume"]
build-command = ["make", "clean", "all"]
